# ===============================
# DATABASE (Neon PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-bold-band-ao2anxbn.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nUcYvlm7E1Wp
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}